services:
  backend:
    image: backend
    container_name: backend
    env_file:
      - .env
    ports:
     - 8000:8000
    restart: unless-stopped
    environment:
     - PYTHONUNBUFFERED=1

  frontend:
    image: frontend
    container_name: frontend
    ports:
     - 80:3000
    restart: unless-stopped

